- .gitignore
- Makefile
- README.md
- compose.yaml
- templates/goose.env
- templates/mcp-atlassian.env
Split the secrets into multiple env files to avoid leaking tokens between services.  I tried to use the Compose-native secrets feature but this did not worked well as secrets are mounted as files (not env vars).
> split secrets into multiple env files

- README.md
Related: https://github.com/packit/jotnar/issues/53
TODO:
Fixes
Related to
> README: add reference to the Openshift namespace

- beeai/agents/backport_agent.py
- beeai/agents/rebase_agent.py
- beeai/agents/triage_agent.py
it looks like this now for standalone runs:
```
{
"id": "c5d19a7a-8136-4b0d-a36d-3f2d2e778d85",
"iteration": 2,
"tool": "think",
"input": {
"next_step": [
"I have analyzed the Jira issue RHEL-78762 and have all the necessary information to make a decision. I will now call the final_answer tool to provide the resolution."
],
"thoughts": "I have analyzed the Jira issue RHEL-78762 and have determined..."
},
"output": "OK"
},
{
"id": "5752deb7-0913-45bf-89ac-017e900610be",
"iteration": 3,
"tool": "final_answer",
"input": {
"data": {
"additional_info_needed": "The fixVersion field in the Jira issue...",
"jira_issue": "RHEL-78762",
"findings": "The Jira issue describes a missing dependency..."
},
"resolution": "clarification-needed"
},
"output": "Message has been sent"
}
]
}
```
I dropped most …
> beeai: pretty print the output

- beeai/Makefile
- beeai/README.md
- beeai/agents/backport_agent.py
- beeai/agents/constants.py
- beeai/agents/rebase_agent.py
- beeai/agents/utils.py
- beeai/compose.yaml
I have been temporarily removing those steps when playing with this locally, but I think this could be good for testing in general.
> Introduce dry-run mode for skipping pushing and creating MRs

- beeai/Containerfile
With the new version of beeai being released, our patch fails to apply, making building new images impossible. As we are waiting for the patch being merged upstream, temporarily pinning until that code is merged and released should be enough. Alternatively, we could regenerate the patch for each new release touching the patched code.
> Temporarily pin beeai to avoid patch application issues for image builds

- Makefile
- README.md
- compose.yaml
- goose-container/Containerfile
- goose-recipes/reverse-dependencies.yaml
- goose-recipes/test-reverse-dependencies.yaml
- scripts/find-package-dependents.py
- scripts/tests/test-find-package-dependents.py
This is a draft merge request to get the reverse-dependencies recipe computing indirect dependents as well. It's Draft status, because, as written, the LLM writes the python script dynamically, and I think it would be better to instead ship a script in-tree.
I also need to check if the input for testing-farm is a source package list (scm module names) or binary package list. if the former, we'll need an additional step to plumb things properly.
> reverse-dependencies: Compute indirect dependents

- .github/workflows/build-and-push.yml
commit 89560a01e360b05e6bef91413cbf2d27286c2a3b reworked the Containerfile to use multiple stages. In the process it also changed the context (working directory) to the toplevel source dir.
The commit neglected to make the associated change in the github build-and-push workflow.
This commit rectifies that oversight.
> workflows: Fix build-and-push workflow following Containerfile changes

- goose-recipes/test-reverse-dependencies.yaml
In trying the reverse dependencies test on c10s, I see we're getting a failure for missing ceph packages.
This is likely because we're only checking AppStream, BaseOS, and CRB, and not some of the more niche repositories.
For now, change the repository to allow for missing dependencies.
> test-reverse-dependencies: Allow incomplete repositories

- scripts/find-package-dependents.py
- scripts/tests/test-find-package-dependents.py
find-package-dependents was passing the user's max_results limit to the generate_direct_dependents function. This would be fine, except we sometimes need more than max_results generated if some of the results are filtered by the user's filter command.
The upshot is the script would sometimes traverse the dependents tree deep instead of wide, leading to performance issues.
This commit drops the max_result limit on generate_direct_dependents, since it's wrong and not needed anyway (because max_results is already handled elsewhere).
This commit also adds a couple of test cases to make sure the problem doesn't creep in again.
> reverse-dependences: Fix bug in find-package-dependents script

- beeai/agents/backport_agent.py
- beeai/agents/rebase_agent.py
- beeai/agents/triage_agent.py
- beeai/agents/utils.py
Here are some fixes for a few type errors and warnings I get when loading the project in vscode.
The most intrusive part here is the workaround for type hinting on redis methods .... this would be improved if some of the repeated code for managing the redis queue was refactored out to a single place.
> Fix some type errors and warnings

- beeai/openshift/cronjob-jira-issue-fetcher.yml
- beeai/openshift/deployment-mcp-atlassian.yml
- beeai/openshift/deployment-mcp-gateway.yml
- beeai/openshift/deployment-redis-commander.yml
- beeai/openshift/deployment-valkey.yml
This should be enough to fit into 4 cpu limit.
As of now we have no data in the metrics, since the deployment is not running yet. We may need to adjust this.
> Decrease cpu limits for non-agent containers

- beeai/agents/backport_agent.py
- beeai/agents/build_agent.py
- beeai/agents/rebase_agent.py
- beeai/agents/triage_agent.py
Enabling parallel tool calls didn't really work, it led to errors like `The model was required to produce a tool call for the 'think' tool, but no tool calls were generated.`.
Disable the option and enforce the think tool as the first tool to be called with a requirement.
> Fix tool calling

- beeai/Containerfile
- beeai/Containerfile.mcp
`centpkg prep` in OpenShift fails because `%{_topdir}` is defined as `/rpmbuild` and that gives permission denied. `%{_topdir}` is based on `$HOME` which is set to be `/`. Fix that.
> Explicitly set HOME in containers

- beeai/openshift/deployment-backport-agent.yml
- beeai/openshift/deployment-mcp-gateway.yml
- beeai/openshift/deployment-rebase-agent.yml
- beeai/openshift/deployment-triage-agent.yml
To prevent issues like:
```
Multi-Attach error for volume "pvc-7be4cb58-c0b2-4c5b-94f3-62babed8b99c"
Volume is already used by pod(s) triage-agent-6b78fbbcfb-f4kbq,
rebase-agent-56449b88bd-qvm2r, backport-agent-84c565555b-dm6kf
```
> Bind agents and MCP gateway to the same node

- .github/workflows/check-in-container.yml
- beeai/.github/workflows/check-in-container.yml
- beeai/Containerfile.tests
- beeai/Makefile
- beeai/Makefile.tests
Cheery-picked from #133 so we can get it merged ideally today
> Maja's GHA for running tests in CI

- README.md
podman-compose or similar is required as well:
```
$ make build
podman compose build
[  331.100290] evm: overlay not supported
Error: looking up compose provider failed
7 errors occurred:
* exec: "/root/.docker/cli-plugins/docker-compose": stat /root/.docker/cli-plugins/docker-compose: no such file or directory
* exec: "/usr/local/lib/docker/cli-plugins/docker-compose": stat /usr/local/lib/docker/cli-plugins/docker-compose: no such file or directory
* exec: "/usr/local/libexec/docker/cli-plugins/docker-compose": stat /usr/local/libexec/docker/cli-plugins/docker-compose: no such file or directory
* exec: "/usr/lib/docker/cli-plugins/docker-compose": stat /usr/lib/docker/cli-plugins/docker-compose: no such file or directory
* exec: "/usr/libexec/docker/cli-plugins/docker-compose": stat …
```
> Fix Prequisities in README.md

- beeai/agents/backport_agent.py
- beeai/agents/log_agent.py
- beeai/agents/rebase_agent.py
- beeai/agents/tasks.py
So it can do `git diff --cached` and examine all files to be committed.
> Stage changes before running log agent

- beeai/agents/tasks.py
In case of an already existing fork created with "centpkg fork", the repository will have the namespace in its name, e.g. centos_rpms_foo. Since we later assume the repository is in /git-repos/RHEL-XXX/package we have to specify the directory name to match the expectations.
> beeai: clone repositories to directory named after the package name

- goose-container/Containerfile
This script is used by many of the workflows and was missing inside the container.
Fixes #169
> goose-container: install missing wait_mcp_server.sh script

- beeai/.gitignore
- beeai/Containerfile.c10s
- beeai/Makefile
- beeai/compose.yaml
- beeai/supervisor/errata_utils.py
- beeai/supervisor/http_utils.py
- beeai/supervisor/jira_utils.py
- beeai/supervisor/main.py
- beeai/supervisor/qe_data.py
- beeai/supervisor/testing_analyst.py
- beeai/supervisor/tools/read_readme.py
- beeai/supervisor/tools/search_resultsdb.py
This merge requestadds a new tool for the supervisor's testing-analyst agent - it searches in resultsdb
(https://github.com/release-engineering/resultsdb) to find test results.
This provides the testing analyst agent a convenient way to locate and check on the results of testing for the Display Systems packages. (Details of what names the tests are under are provided in the downloaded QE data.)
The merge request takes a bit of a roundabout route, there are also commits here:
- To change to how HTTP sessions are handled (because results DB also need the internal Red Hat IT CA cert)
- To change the QE data file format to not duplicate date (because duplicating the long comment about how to find things in resultsdb made the old file format get even bigger and messier.)
- A couple of related …
> supervisor: Add a search_resultsdb tool

- agents/tasks.py
- mcp_server/gitlab_tools.py
- mcp_server/tests/unit/test_gitlab_tools.py
In case the parent repository has been forked a while ago, it is possible that the branch to be worked on in the fork lags behind its counterpart in the parent repository and needs to be updated before running the agents.
> Update fork to match its parent before running agents

- common/tests/unit/test_utils.py
- common/utils.py
- mcp_server/copr_tools.py
- mcp_server/lookaside_tools.py
- mcp_server/utils.py
- supervisor/main.py
This pull request:
- Moves init_kerberos_ticket() to common/utils
- Enhances it a bit:
- If KEYTAB_FILE is not set, but a valid ticket exists, use it
- Raise KerberosError rather than returning None on failure
- Don't spew klist/kinit output on success
- Calls it at initialization of the supervisor subcommands that need to talk to erratatool
> Move init_kerberos_ticket to common and use for supervisor

- Containerfile.c10s
- Containerfile.supervisor
- compose.yaml
Reusing Containerfile.c10s for the supervisor process was a
bit messy - there are a lot of things that the supervisor didn't
need in the image (like the rpmbuild environment), and we were
also adding random divergences between Containerfile.c9s and
Containerfile.c10s to support the supervisor.
> supervisor: use a separate Containerfile

- supervisor/issue_handler.py
- supervisor/testing_analyst.py
Include the related erratum in the prompt so the agent has more context to make an informed decision—particularly in cases where test execution has not been initialized within 6 hours after the erratum moves to QE status.
> Feat: Provide related erratum to the agent

- agents/backport_agent.py
- agents/rebase_agent.py
- agents/tools/wicked_git.py
- agents/triage_agent.py
- agents/utils.py
I suggest going commit by commit in review.
This mainly fixes the apply_patch_finish logic and drops `-3` because it confuses agents with errors saying there are no parent commits
> drop `-3`, fix apply_patch_finish when `--skip` yields more conflicts

- agents/tests/unit/test_tools.py
- agents/tools/wicked_git.py
this implementation prints all files that a patch changes with `git
apply --stat` and if at least one file from the patch is present in the
repo, the function yields the respective N
> discover `git apply -pN`

- openshift/README.md
- openshift/deployment-backport-agent-c10s.yml
- openshift/deployment-backport-agent-c9s.yml
- openshift/deployment-rebase-agent-c10s.yml
- openshift/deployment-rebase-agent-c9s.yml
- openshift/deployment-triage-agent.yml
We're no longer referencing this anywhere in the code for the agents.
> Remove the no-longer-needed GITLAB_USER env var

- Containerfile.c9s-tests
- Containerfile.tests
- agents/backport_agent.py
- agents/tests/unit/conftest.py
- agents/tests/unit/test_backporting.py
- agents/tests/unit/test_tools.py
A typical upstream tarball has this kind of structure:
foobar-1.0.0/README
foobar-1.0.0/code.c
So the backporting agent would use foobar-1.0.0/ as a working directory
and the patches would be applied via `a/code.c` with `-p1`.
Some projects don't do this and instead add more layers, which then
require different levels of `-pN`. Example:
foobar-1.0.0/README
foobar-1.0.0/library/code.c
(i.e. here TLD would be `foobar-1.0.0/library/`)
The main problem here is that some packages utilize different techniques
when a patch does not apply with `-p1`, a common technique is to `pushd`
inside, apply patches, then `popd`.
Well, that's a big problem for us because there is no way to figure out
how we can mimic that in the backporting agent.
This simple patch goes the naive way of setting TLD to the …
> archive TLD: set root archive dir as working dir
