Makefile
goose-container/Containerfile
goose-recipes/backport-fix.yaml

Fixes https://github.com/packit/jotnar/issues/14

Implement initial backporting agent

---

README.md

README: add reference to jotnar quay organization

---

.github/workflows/build-and-push.yml

Related: https://github.com/packit/jotnar/issues/38
TODO:
Fixes
Related to

Add build and push GitHub workflow for BeeAI

---

beeai/Containerfile

... as it is required for Openshift deployment.
Related: https://github.com/packit/jotnar/issues/38
TODO:
Fixes
Related to

Copy `/home/beeai/agents/` in the Containerfile

---

beeai/Containerfile

... as it is required for Openshift.
Related: https://github.com/packit/jotnar/issues/38
TODO:
Fixes
Related to

Change group to `root` for `/home/beeai`

---

beeai/Containerfile

Install `centpkg` in the beeai container

---

beeai/Containerfile

... by names.
TODO:
Fixes
Related to

Sort the packages installed in the beeai container

---

CONTRIBUTING.md

Resolves: https://github.com/packit/jotnar/issues/71
TODO:
Fixes
Related to

Add policy for merging

---

README.md

Add a warning about giving write access to an agent

---

README.md

The README was getting a little out of date, so this commit is just the results of an LLM updating it based on the current state of the tree with a final edit pass done by me.

README.md: Let LLM rewrite README.md

---

beeai/openshift/Makefile
beeai/openshift/README.md
beeai/openshift/deploy.sh

Related: https://github.com/packit/jotnar/issues/38
TODO:
Fixes
Related to

Add instructions to deploy on OpenShift

---

beeai/openshift/configmap-x-beeai-agent-configmap.yml
beeai/openshift/deploy.sh
beeai/openshift/pvc-phoenix-data.yml
beeai/openshift/pvc-valkey-data.yml
beeai/openshift/route-phoenix.yml

Remove namespace field from OpenShift configurations

---

beeai/openshift/README.md
beeai/openshift/configmap-x-beeai-agent-configmap.yml
beeai/openshift/configmap-x-mcp-gateway.yml
beeai/openshift/deployment-backport-agent.yml
beeai/openshift/deployment-mcp-gateway.yml
beeai/openshift/deployment-phoenix.yml
beeai/openshift/deployment-rebase-agent.yml
beeai/openshift/deployment-redis-commander.yml
beeai/openshift/deployment-triage-agent.yml
beeai/openshift/deployment-valkey.yml
beeai/openshift/imagestream-mcp-gateway.yml
beeai/openshift/pvc-mcp-server-git-repos.yml
beeai/openshift/service-mcp-gateway.yml

Add OpenShift configurations for MCP Gateway

---

beeai/agents/backport_agent.py
beeai/agents/constants.py
beeai/agents/rebase_agent.py
beeai/agents/triage_agent.py
beeai/agents/utils.py
beeai/compose.yaml
beeai/mcp_server/jira_tools.py

Add reporting in Jira about agent actions

---

beeai/README.md
beeai/agents/backport_agent.py
beeai/agents/rebase_agent.py
beeai/agents/tools/version_mapper.py
beeai/agents/triage_agent.py
beeai/compose.yaml
beeai/mcp_server/jira_tools.py
beeai/openshift/README.md
beeai/openshift/deployment-mcp-gateway.yml
beeai/templates/rhel-config.json

Let's settle on the logic first, then I will udpate the instructions how to use the new method.

Add CVE checks and integrate to triage agent with workflow

---

beeai/agents/backport_agent.py
beeai/agents/rebase_agent.py
beeai/agents/tasks.py
beeai/agents/triage_agent.py
beeai/agents/utils.py
beeai/compose.yaml
beeai/mcp_server/gateway.py
beeai/mcp_server/jira_tools.py
beeai/mcp_server/tests/unit/test_jira_tools.py

A follow-up to https://github.com/packit/ai-workflows/pull/84 and https://github.com/packit/ai-workflows/pull/86.

Several fixes

---

beeai/agents/backport_agent.py
beeai/agents/constants.py
beeai/agents/rebase_agent.py
beeai/agents/tools/wicked_git.py

You are welcome to provide review on proposed commit title & body, and MR title & descriptions.
Fixes https://github.com/packit/jotnar/issues/85

Provide detailed commit & MR title, body

---

beeai/mcp_server/gitlab_tools.py
beeai/mcp_server/tests/unit/test_gitlab_tools.py
beeai/mcp_server/tests/unit/test_jira_tools.py

...so that we can inspect it ASAP
you can check the labels here: https://gitlab.com/groups/redhat/centos-stream/rpms/-/labels#

set label jotnar_needs_attention on a newly created MR

---

scripts/git-add-patch-non-interactive
testing-farm-sse-bridge/testing_farm_sse_bridge/app.py

I've hit a few issues using the testing-farm-sse-bridge that lead to these changes in the pull request:
1. Allow specifying a list of request ids in the query
2. Fixing a logic error pulling the id token from the bearer token
3. Dropping support for an output format testing farm doesn't currently use
Also, since I'm leaning heavily on AI here, I'm adding a script I had AI write so that AI could stage the changes into commits.

Testing farm sse bridge fixes

---

beeai/README.md
beeai/templates/beeai-agent.env
beeai/templates/mcp-atlassian.env
beeai/templates/mcp-gateway.env

Add more details to make it easier for the new contributors.
Resolves: https://github.com/packit/jotnar/issues/106
TODO:
Fixes
Related to

Update `README.md` for the BeeAI agents

---

beeai/mcp_server/gitlab_tools.py

Should help with https://github.com/packit/jotnar/issues/142

MR create: log error when setting a label

---

beeai/agents/backport_agent.py
beeai/agents/build_agent.py
beeai/agents/rebase_agent.py
beeai/agents/tools/specfile.py
beeai/agents/triage_agent.py
beeai/agents/utils.py
beeai/beeai-instrumentation.patch
beeai/common/models.py
beeai/mcp_server/copr_tools.py
beeai/mcp_server/tests/unit/test_copr.py

There will be a follow-up to add the build agent to the backport workflow as well.

Build verification

---

beeai/Makefile.tests
beeai/agents/backport_agent.py
beeai/agents/constants.py
beeai/agents/rebase_agent.py
beeai/agents/tasks.py
beeai/agents/tools/version_mapper.py
beeai/agents/triage_agent.py
beeai/mcp_server/jira_tools.py
beeai/mcp_server/tests/unit/test_jira_tools.py

Fixes packit/jotnar#118
I implemented this only for the service mode (not the direct one), let me know if you have any concerns regarding this.
TODO:
Tested in https://issues.redhat.com/browse/RHEL-109066 and https://issues.redhat.com/browse/RHEL-109248 so far.

Implement labels and status changes

---

beeai/agents/triage_agent.py
beeai/mcp_server/jira_tools.py
beeai/mcp_server/tests/unit/test_jira_tools.py

Verify author of Jira issue for rebase resolutions

---

beeai/openshift/cronjob-jira-issue-fetcher.yml
beeai/openshift/deployment-backport-agent.yml
beeai/openshift/deployment-mcp-gateway.yml
beeai/openshift/deployment-phoenix.yml
beeai/openshift/deployment-rebase-agent.yml
beeai/openshift/deployment-redis-commander.yml
beeai/openshift/deployment-triage-agent.yml
beeai/openshift/deployment-valkey.yml

Already applied for most of these.

Trigger updates on imagestream changes in Openshift

---

beeai/mcp_server/gitlab_tools.py
beeai/mcp_server/tests/unit/test_gitlab_tools.py

also fix related tests
Now finally fixing https://github.com/packit/jotnar/issues/142

add retry mechanism for pr.add_label

---

beeai/agents/tools/specfile.py
beeai/agents/tools/text.py
beeai/mcp_server/tests/unit/test_gitlab_tools.py

Also make the `str_replace` tool fail when no replacement was done.

Raise errors from simple tools

---

beeai/agents/backport_agent.py
beeai/agents/build_agent.py
beeai/agents/rebase_agent.py
beeai/agents/tools/commands.py

- Be more explicit about tool usage
- Add timeout to `run_shell_command`
- Instead of changing global CWD pass the correct path to `run_shell_command`

Tool improvements

---

beeai/README.md
beeai/jira_issue_fetcher/jira_issue_fetcher.py
beeai/templates/jira-issue-fetcher.env

The second part should be sufficient, just wanted to stay safe 😅

By default filter jotnar-assigned issues

---

beeai/openshift/cronjob-jira-issue-fetcher.yml
beeai/openshift/deployment-backport-agent.yml
beeai/openshift/deployment-mcp-gateway.yml
beeai/openshift/deployment-phoenix.yml
beeai/openshift/deployment-rebase-agent.yml
beeai/openshift/deployment-redis-commander.yml
beeai/openshift/deployment-triage-agent.yml
beeai/openshift/deployment-valkey.yml
beeai/openshift/pvc-phoenix-data.yml

This reverts commit d62d219b5b988d54f784846d676e051edac9b1f2.

Revert "Trigger updates on imagestream changes in Openshift"

---

beeai/agents/backport_agent.py
beeai/agents/rebase_agent.py

https://gitlab.com/redhat/centos-stream/rpms/python-pluggy/-/merge_requests/9

Changelog: start with capital 'R' for 'resolves'

---

goose-container/Containerfile

goose-container: fix GOOSE_VERSION var not properly expanding

---

beeai/agents/backport_agent.py
beeai/agents/build_agent.py
beeai/agents/log_agent.py
beeai/agents/rebase_agent.py
beeai/agents/triage_agent.py
beeai/agents/utils.py

https://github.com/packit/jotnar/issues/180
Fixes https://github.com/packit/jotnar/issues/182
refactoring:
`provide ChatModel via an util function`

set ChatModel timeout to 1200 and set temperature to 0.6

---

.gitignore
beeai/.gitignore
beeai/Containerfile.c10s
beeai/Makefile
beeai/README-agents.md
beeai/README-supervisor.md
beeai/README.md
beeai/compose.yaml
beeai/pyproject.toml
beeai/supervisor/errata_utils.py
beeai/supervisor/erratum_handler.py
beeai/supervisor/issue_handler.py
beeai/supervisor/jira_utils.py
beeai/supervisor/main.py
beeai/supervisor/supervisor_types.py
beeai/supervisor/testing_analyst.py
beeai/supervisor/tools/read_readme.py
beeai/supervisor/work_item_handler.py
beeai/supervisor/work_queue.py
beeai/templates/supervisor.env

Add a new workflow supervisor to handle coordinating the test and release of builds once the merge request made be the agents is merged.
There are two major components: the collector (queries JIRA and erratatool for what issues and errata need processing) and the executor (executes tasks).
* README.md is split into README.md / README-agents.md / README.supervisor.md
* compose.yaml now has two profiles "agents" and "supervisor"
* A single image is used for both the agents and the supervisor
The structure here should be pretty workable, but the actual implementation of checks and actions is still undone to a large amount - in particular, *no* actions are implemented at all.
The integration into beeai/ feels a little intrusive - but I do think it makes sense to have a single codebase with …

Add supervisor components alongside the current  agents

---

agents/backport_agent.py
agents/tasks.py
mcp_server/gitlab_tools.py
mcp_server/tests/unit/test_gitlab_tools.py

Where we can also access the private repos.

Clone repos in the mcp gateway

---

agents/tests/unit/test_tools.py
agents/tools/wicked_git.py

Nikola confirmed that the context just doesn't work as a shared object
b/w tools, we have Tool.options for that

rewrite implementation of base_head_commit

---

Containerfile.c10s
Containerfile.c9s

This should fix the broken instrumentation with rebase agent, where the serialization is used only for logging, however I'm not sure if it won't break something elsewhere (in BeeAI).

Fix serialization of sets

---

supervisor/jira_utils.py

Just a cleanup to replace all the url params to be passed as dict. Note: didn't change the request in get_issue because it increases the response time. Better keep it as it is.

Clean up: Pass url params as dict

---

supervisor/jira_utils.py
supervisor/supervisor_types.py

Make FullIssue include the description of the JIRA issue. Even though it might not be the most relevant information for the agent to analyze, it should be include.
https://github.com/packit/jotnar/issues/195

Feat: Add description attribute to FullIssue

---

.github/workflows/build-and-push.yml

Apparently I can't get a 1-word patch right, let's try a 1-character patch!

workflows: build-and-push: workflow_dispatch not workflow-dispatch

---

agents/utils.py

https://github.com/i-am-bee/beeai-framework/issues/1145#issuecomment-3374304599

Disable required tool choice support for Gemini
